services:
  db:
    image: postgres:latest
    container_name: mi_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - mi_red
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy  # Esperar hasta que DB esté lista 
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge

volumes:
  pgdata:
